"""Perplexity from token log probabilities returned by local Ollama."""

import json
import math
from typing import Any
from urllib.error import URLError
from urllib.request import Request, urlopen

import pandas as pd


def perplexity_from_logprobs(logprobs: list[float]) -> float:
    """Return exp(-mean(log probability)) for a generated token sequence."""
    if not logprobs:
        raise ValueError("At least one token log probability is required.")
    return math.exp(-sum(logprobs) / len(logprobs))


def token_probability_table(token_details: list[dict[str, Any]]) -> pd.DataFrame:
    """Make token-level probabilities inspectable in a classroom table."""
    rows = []
    for position, item in enumerate(token_details, start=1):
        alternatives = item.get("top_logprobs", []) or []
        chosen_token = item.get("token", "")
        other_alternatives = [candidate for candidate in alternatives if candidate.get("token", "") != chosen_token]
        best_alternative = max(other_alternatives, key=lambda candidate: candidate["logprob"], default=None)
        chosen_probability = math.exp(float(item["logprob"]))
        best_alternative_probability = (
            math.exp(float(best_alternative["logprob"])) if best_alternative is not None else 0.0
        )
        rows.append(
            {
                "position": position,
                "token": repr(chosen_token),
                "logprob": float(item["logprob"]),
                "probability": chosen_probability,
                "surprisal": -float(item["logprob"]),
                "best_alternative": repr(best_alternative.get("token", "")) if best_alternative else "",
                "best_alternative_probability": best_alternative_probability,
                "alternative_margin": best_alternative_probability - chosen_probability,
                "top_alternatives": ", ".join(
                    f"{candidate.get('token', '')!r}: {math.exp(float(candidate['logprob'])):.3f}"
                    for candidate in alternatives[:3]
                ),
            }
        )
    return pd.DataFrame(rows)


def perplexity_summary(token_details: list[dict[str, Any]]) -> dict[str, float]:
    """Translate perplexity into token-level quantities students can interpret."""
    logprobs = [float(item["logprob"]) for item in token_details]
    perplexity = perplexity_from_logprobs(logprobs)
    return {
        "average_surprisal": -sum(logprobs) / len(logprobs),
        "geometric_mean_probability": math.exp(sum(logprobs) / len(logprobs)),
        "perplexity": perplexity,
    }


def generated_perplexity(
    prompt: str,
    model: str,
    host: str = "http://127.0.0.1:11434",
    max_tokens: int = 64,
) -> dict[str, Any]:
    """Generate deterministically with Ollama and calculate output perplexity.

    This measures the probability of the response generated by the model, not
    teacher-forced perplexity of an arbitrary reference string.
    """
    payload = json.dumps(
        {
            "model": model,
            "prompt": prompt,
            "stream": False,
            "raw": True,
            "logprobs": True,
            "top_logprobs": 3,
            "options": {"temperature": 0, "num_predict": max_tokens},
        }
    ).encode("utf-8")
    request = Request(
        f"{host.rstrip('/')}/api/generate",
        data=payload,
        headers={"Content-Type": "application/json"},
        method="POST",
    )
    try:
        with urlopen(request, timeout=120) as response:  # noqa: S310
            result = json.loads(response.read().decode("utf-8"))
    except URLError as error:
        raise RuntimeError("Ollama is not reachable. Start it and verify OLLAMA_HOST.") from error
    token_details = result.get("logprobs", [])
    token_logprobs = [float(item["logprob"]) for item in token_details]
    if not token_logprobs:
        raise RuntimeError(
            "Ollama did not return token log probabilities. This server/model combination cannot calculate perplexity."
        )
    return {
        "model": model,
        "response": result.get("response", ""),
        "token_count": len(token_logprobs),
        "token_details": token_details,
        "perplexity": perplexity_from_logprobs(token_logprobs),
    }
